#!/usr/bin/env bash
# Wires the lock-screen route Live Activity into the flutter-create-
# regenerated ios/ project:
#   1. copies the committed Swift sources (mobile/ios_widget/) into place,
#   2. injects the RouteActivity widget-extension target + Runner sources
#      via tool/ios-live-activity.rb (xcodeproj gem),
#   3. registers the method-channel bridge in AppDelegate.swift,
#   4. sets NSSupportsLiveActivities in the Runner Info.plist.
# macOS only; idempotent; run from the app dir (mobile/) AFTER
# tool/ios-appauth.sh. CI runs it on every build because ios/ is
# regenerated from the bare template there.
set -euo pipefail

[ -d ios/Runner.xcodeproj ] || { echo "no ios project; skipping live activity setup" >&2; exit 0; }
PB=/usr/libexec/PlistBuddy
[ -x "$PB" ] || { echo "PlistBuddy not found; skipping (non-macOS?)" >&2; exit 0; }

# --- 1. sources -------------------------------------------------------------
mkdir -p ios/RouteActivity
cp ios_widget/RouteActivityAttributes.swift ios/RouteActivity/
cp ios_widget/RouteActivityWidget.swift ios/RouteActivity/
cp ios_widget/RouteActivityInfo.plist ios/RouteActivity/Info.plist
cp ios_widget/RouteActivityAttributes.swift ios/Runner/
cp ios_widget/LiveActivityBridge.swift ios/Runner/

# --- 2. project surgery -----------------------------------------------------
# xcodeproj ships with CocoaPods: as a plain gem on CI runners, inside the
# Homebrew keg locally.
if ruby -e "require 'xcodeproj'" 2>/dev/null; then
  ruby tool/ios-live-activity.rb
elif [ -x /opt/homebrew/bin/pod ]; then
  # Homebrew keg: /opt/homebrew/Cellar/cocoapods/<ver>/{bin,libexec}; the
  # bundled gems (xcodeproj included) live under libexec.
  KEG="$(dirname "$(dirname "$(readlink -f /opt/homebrew/bin/pod)")")"
  GEM_PATH="$KEG/libexec" ruby tool/ios-live-activity.rb
else
  echo "ERROR: ruby xcodeproj gem unavailable — cannot inject the widget extension" >&2
  exit 1
fi

# --- 3. AppDelegate registration -------------------------------------------
# The template AppDelegate is regenerated by flutter create; insert the
# bridge registration after plugin registration (idempotent by marker).
AD=ios/Runner/AppDelegate.swift
if [ -f "$AD" ] && ! grep -q LiveActivityBridge "$AD"; then
  python3 - "$AD" <<'EOF'
import sys
path = sys.argv[1]
src = open(path).read()
# Flutter 3.35+ template registers plugins via the implicit-engine bridge;
# older templates in didFinishLaunching. Handle both.
new_anchor = "GeneratedPluginRegistrant.register(with: engineBridge.pluginRegistry)"
old_anchor = "GeneratedPluginRegistrant.register(with: self)"
if new_anchor in src:
    inject = new_anchor + """
    if let registrar = engineBridge.pluginRegistry.registrar(forPlugin: "LiveActivityBridge") {
      LiveActivityBridge.register(messenger: registrar.messenger())
    }"""
    src = src.replace(new_anchor, inject, 1)
elif old_anchor in src:
    inject = old_anchor + """
    if let controller = window?.rootViewController as? FlutterViewController {
      LiveActivityBridge.register(messenger: controller.binaryMessenger)
    }"""
    src = src.replace(old_anchor, inject, 1)
else:
    sys.exit("AppDelegate template changed: no known registration anchor")
open(path, "w").write(src)
EOF
  echo "registered LiveActivityBridge in AppDelegate"
fi
grep -q LiveActivityBridge "$AD" || { echo "ERROR: bridge registration missing" >&2; exit 1; }

# --- 4. Runner plist flag ---------------------------------------------------
PLIST=ios/Runner/Info.plist
"$PB" -c "Set :NSSupportsLiveActivities true" "$PLIST" 2>/dev/null \
  || "$PB" -c "Add :NSSupportsLiveActivities bool true" "$PLIST"
echo "route live activity wired"
